name: "Run provisioning on ubuntu"
"on":
  push:
  pull_request:
  schedule:
    - cron: "42 4 * * 0"
  workflow_dispatch:

jobs:
  pyinfra_lint:
    name: "pyinfra lint"
    runs-on: ubuntu-24.04
    steps:
      - name: "set default branch"
        run: git config --global init.defaultBranch main

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1

      - name: "install dependencies"
        run: uv sync --frozen --all-extras

      - name: "pytest"
        run: uv run pytest

      - name: "ruff check"
        run: uv run ruff check .

      - name: "mypy"
        run: uv run mypy .

      - name: "run prettier"
        run: |
          # renovate: datasource=docker depName=ghcr.io/bacluc/prettier-image/prettier-image
          prettier_image_version="5.1.0"
          docker run --rm -v $PWD:/workdir -w /workdir -u $UID ghcr.io/bacluc/prettier-image/prettier-image:${prettier_image_version}
          git diff --exit-code

  run_pyinfra:
    name: "Run pyinfra on ubuntu"
    runs-on: ubuntu-24.04
    steps:
      - name: "set default branch"
        run: git config --global init.defaultBranch main

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1

      - name: "install dependencies"
        run: uv sync --frozen

      - name: "run pyinfra"
        run: uv run scripts/run_pyinfra_local.py

      - name: "run update-script"
        run: sudo update-script

      - name: "run cleanup-script"
        run: sudo cleanup-script

      - name: "run pyinfra a second time"
        run: uv run scripts/run_pyinfra_local.py
